input_pdf: /path/to/input.pdf
output_csv: /path/to/output.csv
output_images_dir: /path/to/output_images

draw_roi: true
draw_ocr_boxes: true
save_images: true

rois:
  tarango:
    x0: 0.7326
    y0: 0.0089
    x1: 0.9968
    y1: 0.1788
  roberts:
    x0: 0.7202
    y0: 0.0114
    x1: 0.9972
    y1: 0.1323
  roadstar:
    x0: 0.7187
    y0: 0.0020
    x1: 0.9977
    y1: 0.2154
  portillio:
    x0: 0.6677
    y0: 0.0078
    x1: 0.9978
    y1: 0.1445

default_roi: roberts
